"use client";

import { useState, useEffect } from "react";
import { useTranslations, useLocale } from "next-intl";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DataTable, type Column } from "@/components/shared/data-table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Plus, FileText } from "lucide-react";
import { toast } from "sonner";
import { getLocalizedName } from "@/lib/utils/locale";

type PO = {
  id: string;
  poNumber: string;
  supplier: { id: string; name: Record<string, string>; shortName: string | null };
  status: string;
  orderDate: string;
  expectedDeliveryDate: string | null;
  totalAmount: number;
  autoGenerated: boolean;
  items: { id: string }[];
};

const STATUS_COLORS: Record<string, "default" | "secondary" | "destructive" | "outline"> = {
  draft: "secondary",
  sent: "outline",
  confirmed: "default",
  partially_received: "default",
  received: "default",
  cancelled: "destructive",
};

export default function ProcurementPage() {
  const t = useTranslations();
  const locale = useLocale();
  const router = useRouter();
  const [pos, setPos] = useState<PO[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState("__all__");

  useEffect(() => {
    fetchPOs();
  }, []);

  async function fetchPOs() {
    try {
      const res = await fetch("/api/procurement/purchase-orders");
      if (res.ok) setPos(await res.json());
    } catch {
      toast.error("Failed to load purchase orders");
    } finally {
      setLoading(false);
    }
  }

  const filtered = statusFilter === "__all__" ? pos : pos.filter((p) => p.status === statusFilter);

  const columns: Column<PO>[] = [
    {
      key: "poNumber",
      header: t("procurement.poNumber"),
      sortable: true,
      render: (row) => (
        <div className="flex items-center gap-2">
          <span className="font-mono text-sm">{row.poNumber}</span>
          {row.autoGenerated && (
            <Badge variant="outline" className="text-xs">Auto</Badge>
          )}
        </div>
      ),
    },
    {
      key: "supplier",
      header: t("procurement.supplier"),
      sortable: true,
      accessor: (row) => row.supplier.shortName || getLocalizedName(row.supplier.name, locale),
      render: (row) => (
        <span className="font-medium">
          {row.supplier.shortName || getLocalizedName(row.supplier.name, locale)}
        </span>
      ),
    },
    {
      key: "orderDate",
      header: t("procurement.orderDate"),
      sortable: true,
      render: (row) => new Date(row.orderDate).toLocaleDateString(),
    },
    {
      key: "expectedDeliveryDate",
      header: t("procurement.expectedDeliveryDate"),
      sortable: true,
      render: (row) =>
        row.expectedDeliveryDate
          ? new Date(row.expectedDeliveryDate).toLocaleDateString()
          : "—",
    },
    {
      key: "items",
      header: t("procurement.items"),
      render: (row) => `${row.items.length} items`,
    },
    {
      key: "totalAmount",
      header: t("procurement.total"),
      sortable: true,
      render: (row) => `$${Number(row.totalAmount).toFixed(2)}`,
    },
    {
      key: "status",
      header: t("common.status"),
      sortable: true,
      render: (row) => (
        <Badge variant={STATUS_COLORS[row.status] || "secondary"}>
          {t(`procurement.poStatuses.${row.status}` as never)}
        </Badge>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <h1 className="text-2xl font-bold">{t("procurement.purchaseOrders")}</h1>
        <Button onClick={() => router.push(`/${locale}/procurement/new`)}>
          <Plus className="me-2 h-4 w-4" />
          {t("procurement.newPurchaseOrder")}
        </Button>
      </div>

      <div className="flex flex-col sm:flex-row sm:items-center gap-3">
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-full sm:w-48">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="__all__">{t("common.all")} {t("common.status")}</SelectItem>
            {["draft", "sent", "confirmed", "partially_received", "received", "cancelled"].map((s) => (
              <SelectItem key={s} value={s}>
                {t(`procurement.poStatuses.${s}` as never)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            {t("procurement.purchaseOrders")} ({filtered.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <p className="text-muted-foreground">{t("common.loading")}</p>
          ) : (
            <DataTable
              data={filtered}
              columns={columns}
              searchPlaceholder={`${t("common.search")}...`}
              searchFn={(row, q) =>
                row.poNumber.toLowerCase().includes(q) ||
                (row.supplier.shortName || "").toLowerCase().includes(q)
              }
              onRowClick={(row) => router.push(`/${locale}/procurement/${row.id}`)}
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}
