import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { generateReorderSuggestions } from "@/lib/services/auto-reorder";
import { prisma } from "@/lib/prisma";

export async function GET() {
  const session = await getServerSession(authOptions);
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const suggestions = await generateReorderSuggestions();
  return NextResponse.json(suggestions);
}

// Approve suggestions and convert to draft POs
export async function POST(request: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || !["ADMIN", "MANAGER"].includes(session.user.role)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  const body = await request.json();
  // body.items: [{ materialId, supplierId, quantity, unitPrice?, unit }]

  // Group by supplier
  const bySupplier = new Map<string, typeof body.items>();
  for (const item of body.items) {
    const key = item.supplierId;
    if (!bySupplier.has(key)) bySupplier.set(key, []);
    bySupplier.get(key)!.push(item);
  }

  const createdPOs = [];
  const today = new Date();
  const dateStr = today.toISOString().slice(0, 10).replace(/-/g, "");

  for (const [supplierId, items] of bySupplier) {
    const prefix = `PO-${dateStr}-`;
    const last = await prisma.purchaseOrder.findFirst({
      where: { poNumber: { startsWith: prefix } },
      orderBy: { poNumber: "desc" },
    });
    const seq = last
      ? String(parseInt(last.poNumber.slice(-4)) + 1).padStart(4, "0")
      : "0001";

    // Get supplier lead time
    const supplier = await prisma.supplier.findUnique({
      where: { id: supplierId },
    });
    const expectedDate = new Date();
    expectedDate.setDate(expectedDate.getDate() + (supplier?.leadTimeDays || 3));

    // Adjust for delivery days
    const deliveryDays = (supplier?.deliveryDays as number[]) || [];
    if (deliveryDays.length > 0) {
      let attempts = 0;
      while (!deliveryDays.includes(expectedDate.getDay()) && attempts < 7) {
        expectedDate.setDate(expectedDate.getDate() + 1);
        attempts++;
      }
    }

    let subtotal = 0;
    const poItems = items.map(
      (item: { materialId: string; quantity: number; unitPrice?: number; unit?: string }, idx: number) => {
        const totalPrice = (item.quantity || 0) * (item.unitPrice || 0);
        subtotal += totalPrice;
        return {
          rawMaterialId: item.materialId,
          quantityOrdered: item.quantity,
          unit: item.unit || "KG",
          unitPrice: item.unitPrice || null,
          totalPrice: totalPrice || null,
          sortOrder: idx,
        };
      }
    );

    const po = await prisma.purchaseOrder.create({
      data: {
        poNumber: `${prefix}${seq}`,
        supplierId,
        status: "draft",
        expectedDeliveryDate: expectedDate,
        subtotal,
        totalAmount: subtotal,
        autoGenerated: true,
        createdById: session.user.id,
        items: { create: poItems },
      },
    });

    createdPOs.push(po);
  }

  return NextResponse.json(createdPOs, { status: 201 });
}
